/**
 * Icon Names Type
 * Auto-generated from SVG files
 */

export type IconName =
  'Accessibilitycirclefilled' |
  'Accessibilitycircleoutlined' |
  'Addcirclefilled' |
  'Addcircleoutlined' |
  'Addfilled' |
  'Addoutlined' |
  'Applefilled' |
  'Appleoutlined' |
  'Appstorefilled' |
  'Appstoreoutlined' |
  'Arrowdownloadfilled' |
  'Arrowdownloadoutlined' |
  'Arrowlocationfilled' |
  'Arrowlocationoutlined' |
  'Arrowlogoutfilled' |
  'Arrowlogoutoutlined' |
  'Arrowmaximizefilled' |
  'Arrowmaximizeoutlined' |
  'Arrowminimizefilled' |
  'Arrowminimizeoutlined' |
  'Arrowopenfilled' |
  'Arrowopenoutlined' |
  'Arrowscirclefilleddown' |
  'Arrowscirclefilledleft' |
  'Arrowscirclefilledright' |
  'Arrowscirclefilledup' |
  'Arrowscircleoutlineddown' |
  'Arrowscircleoutlinedleft' |
  'Arrowscircleoutlinedright' |
  'Arrowscircleoutlinedup' |
  'Arrowsfilleddown' |
  'Arrowsfilledleft' |
  'Arrowsfilledright' |
  'Arrowsfilledup' |
  'Arrowsoutlineddown' |
  'Arrowsoutlinedleft' |
  'Arrowsoutlinedright' |
  'Arrowsoutlinedup' |
  'ArrowswapHorizontalfilled' |
  'ArrowswapHorizontaloutlined' |
  'ArrowswapVerticalfilled' |
  'ArrowswapVerticaloutlined' |
  'Arrowuploadfilled' |
  'Arrowuploadoutlined' |
  'Attachfilled' |
  'Attachoutlined' |
  'Bankfilled' |
  'Bankoutlined' |
  'BeerbottleMultipleAddfilled' |
  'BeerbottleMultipleAddoutlined' |
  'BeerbottleMultiplefilled' |
  'BeerbottleMultipleoutlined' |
  'BeerbottleRayfilled' |
  'BeerbottleRayoutlined' |
  'Beerbottlefilled' |
  'Beerbottleoutlined' |
  'Beermultiplefilled' |
  'Beermultipleoutlined' |
  'Bellfilled' |
  'Bellnotificationfilled' |
  'Bellnotificationoutlined' |
  'Bellofffilled' |
  'Belloffoutlined' |
  'Belloutlined' |
  'Blockfilled' |
  'Blockoutlined' |
  'Bookcontactsfilled' |
  'Bookcontactsoutlined' |
  'Bookfilled' |
  'Bookmarkfilled' |
  'Bookmarkoutlined' |
  'Bookopenfilled' |
  'Bookopenoutlined' |
  'Bookoutlined' |
  'BottlecapQrCodefilled' |
  'BottlecapQrCodeoutlined' |
  'Bottlecapfilled' |
  'Bottlecapoutlined' |
  'Boxaddfilled' |
  'Boxaddoutlined' |
  'Boxcheckmarkfilled' |
  'Boxcheckmarkoutlined' |
  'Boxclockfilled' |
  'Boxclockoutlined' |
  'Boxerrorfilled' |
  'Boxerroroutlined' |
  'Boxfilled' |
  'Boxoutlined' |
  'Boxsearchfilled' |
  'Boxsearchoutlined' |
  'Boxwarningfilled' |
  'Boxwarningoutlined' |
  'Briefcasefilled' |
  'Briefcaseoutlined' |
  'Calendar1filled' |
  'Calendar1outlined' |
  'Calendar31filled' |
  'Calendar31outlined' |
  'Calendarclockfilled' |
  'Calendarclockoutlined' |
  'CalendarcreditCardfilled' |
  'CalendarcreditCardoutlined' |
  'Calendaremptyfilled' |
  'Calendaremptyoutlined' |
  'Calendarfilled' |
  'Calendarofffilled' |
  'Calendaroffoutlined' |
  'Calendaroutlined' |
  'Calendarstarfilled' |
  'Calendarstaroutlined' |
  'Callfilled' |
  'Callinboundfilled' |
  'Callinboundoutlined' |
  'Callofffilled' |
  'Calloffoutlined' |
  'Calloutboundfilled' |
  'Calloutboundoutlined' |
  'Calloutlined' |
  'Camerafilled' |
  'Cameraoutlined' |
  'Caretfilleddown' |
  'Caretfilledleft' |
  'Caretfilledright' |
  'Caretfilledup' |
  'Caretoutlineddown' |
  'Caretoutlinedleft' |
  'Caretoutlinedright' |
  'Caretoutlinedup' |
  'Cashbackfilled' |
  'Cashbackoutlined' |
  'Categoryaddfilled' |
  'Categoryaddoutlined' |
  'Categoryfilled' |
  'Categoryoutlined' |
  'Checkboxesfilledchecked' |
  'Checkboxesfilledindeterminate' |
  'Checkboxesfilledunchecked' |
  'Checkboxesoutlinedchecked' |
  'Checkboxesoutlinedindeterminate' |
  'Checkboxesoutlinedunchecked' |
  'Checkmarkcirclefilled' |
  'Checkmarkcircleoutlined' |
  'Checkmarkfilled' |
  'Checkmarkoutlined' |
  'Checkmarkstarburstfilled' |
  'Checkmarkstarburstoutlined' |
  'Chevronfilleddown' |
  'Chevronfilledleft' |
  'Chevronfilledright' |
  'Chevronfilledup' |
  'Chevronoutlineddown' |
  'Chevronoutlinedleft' |
  'Chevronoutlinedright' |
  'Chevronoutlinedup' |
  'Choppfilled' |
  'Choppoutlined' |
  'Clipboardaddfilled' |
  'Clipboardaddoutlined' |
  'Clipboardcheckmarkfilled' |
  'Clipboardcheckmarkoutlined' |
  'Clipboardemptyfilled' |
  'Clipboardemptyoutlined' |
  'Clipboardfilled' |
  'Clipboardourlined' |
  'Clockfastfilled' |
  'Clockfastoutlined' |
  'Clockfilled' |
  'Clockoutlined' |
  'Cocktailfilled' |
  'Cocktailoutlined' |
  'Codefilled' |
  'Codeoutlined' |
  'Coffeefilled' |
  'Coffeeoutlined' |
  'Coincryptofilled' |
  'Coincryptooutlined' |
  'Coineurofilled' |
  'Coineurooutlined' |
  'Coinfilled' |
  'Coinoutlined' |
  'Coinpoundfilled' |
  'Coinpoundoutlined' |
  'Coinyenfilled' |
  'Coinyenoutlined' |
  'Contactcardfilled' |
  'Contactcardoutlined' |
  'Copyfilled' |
  'Copyoutlined' |
  'CreditcardAddfilled' |
  'CreditcardAddoutlined' |
  'CreditcardErrorfilled' |
  'CreditcardErroroutlined' |
  'Creditcardfilled' |
  'Creditcardoutlined' |
  'Dataareafilled' |
  'Dataareaoutlined' |
  'DatabarHorizontalAscendingfilled' |
  'DatabarHorizontalAscendingoutlined' |
  'DatabarHorizontalDescendingfilled' |
  'DatabarHorizontalDescendingoutlined' |
  'DatabarVerticalAscendingfilled' |
  'DatabarVerticalAscendingoutlined' |
  'DatabarVerticalDescendingfilled' |
  'DatabarVerticalDescendingoutlined' |
  'Datafunnelfilled' |
  'Datafunneloutlined' |
  'Datahistogramfilled' |
  'Datahistogramoutlined' |
  'Datalinefilled' |
  'Datalineoutlined' |
  'Datapiefilled' |
  'Datapieoutlined' |
  'Datascatterfilled' |
  'Datascatteroutlined' |
  'Desktopfilled' |
  'Desktopoutlined' |
  'Dismisscirclefilled' |
  'Dismisscircleoutlined' |
  'Dismissfilled' |
  'Dismissoutlined' |
  'Documentbillfilled' |
  'Documentbilloutlined' |
  'Documentcheckmarkfilled' |
  'Documentcheckmarkoutlined' |
  'Documentclockfilled' |
  'Documentclockoutlined' |
  'Documentemptyfilled' |
  'Documentemptyoutlined' |
  'Documentfilled' |
  'Documentoutlined' |
  'Documentstarfilled' |
  'Documentstaroutlined' |
  'Donutfilled' |
  'Donutoutlined' |
  'Doublearrowfilleddown' |
  'Doublearrowfilledleft' |
  'Doublearrowfilledright' |
  'Doublearrowfilledup' |
  'Doublearrowoutlineddown' |
  'Doublearrowoutlinedleft' |
  'Doublearrowoutlinedright' |
  'Doublearrowoutlinedup' |
  'Earthfilled' |
  'Earthoutlined' |
  'Editfilled' |
  'Editoutlined' |
  'Emojiangryfilled' |
  'Emojiangryoutlined' |
  'Emojidisappointedfilled' |
  'Emojidisappointedoutlined' |
  'Emojilaughfilled' |
  'Emojilaughoutlined' |
  'Emojimehfilled' |
  'Emojimehoutlined' |
  'EmojisadSlightfilled' |
  'EmojisadSlightoutlined' |
  'Emojisadfilled' |
  'Emojisadoutlined' |
  'EmojismileSlightfilled' |
  'EmojismileSlightoutlined' |
  'Emojismilefilled' |
  'Emojismileoutlined' |
  'Emojisurprisefilled' |
  'Emojisurpriseoutlined' |
  'Equalfilled' |
  'Equaloutlined' |
  'Eyefilled' |
  'Eyeofffilled' |
  'Eyeoffoutlined' |
  'Eyeoutlined' |
  'Facebookfilled' |
  'Facebookoutlined' |
  'Filterfilled' |
  'Filteroutlined' |
  'Fingerprintfilled' |
  'Fingerprintoutlined' |
  'Flashlightfilled' |
  'Flashlightofffilled' |
  'Flashlightoffoutlined' |
  'Flashlightoutlined' |
  'Flashlightvariantfilled' |
  'Flashlightvariantoutlined' |
  'Folderaddfilled' |
  'Folderaddoutlined' |
  'Folderfilled' |
  'Folderopenfilled' |
  'Folderopenoutlined' |
  'Folderoutlined' |
  'Fullscreenfilledmaximize' |
  'Fullscreenfilledminimize' |
  'Fullscreenoutlinedmaximize' |
  'Fullscreenoutlinedminimize' |
  'Giftfilled' |
  'Giftoutlined' |
  'Globefilled' |
  'Globeoutlined' |
  'Googlefilled' |
  'Googleoutlined' |
  'Googleplayfilled' |
  'Googleplayoutlined' |
  'Heartfilled' |
  'Heartoutlined' |
  'Helpcirclefilled' |
  'Helpcircleoutlined' |
  'Historyfilled' |
  'Historyoutlined' |
  'Homefilled' |
  'Homeoutlined' |
  'Housefilled' |
  'Houseoutlined' |
  'Icepopfilled' |
  'Icepopoutlined' |
  'Imagefilled' |
  'Imageofffilled' |
  'Imageoffoutlined' |
  'Imageoutlined' |
  'Inboxfilled' |
  'Inboxoutlined' |
  'Inboxreceivefilled' |
  'Inboxreceiveoutlined' |
  'Inboxsendfilled' |
  'Inboxsendoutlined' |
  'Infocirclefilled' |
  'Infocircleoutlined' |
  'Instagramfilled' |
  'Instagramoutlined' |
  'Juicefilled' |
  'Juiceoutlined' |
  'Lightbulbcirclefilled' |
  'Lightbulbcircleoutlined' |
  'Lightbulbfilamentfilled' |
  'Lightbulbfilamentoutlined' |
  'Lightbulbfilled' |
  'Lightbulbofffilled' |
  'Lightbulboffoutlined' |
  'Lightbulboutlined' |
  'Linkedinfilled' |
  'Linkedinoutlined' |
  'Listfilled' |
  'Listoutlined' |
  'Locationfilled' |
  'Locationoutlined' |
  'Lockfilled' |
  'Lockopenfilled' |
  'Lockopenoutlined' |
  'Lockoutlined' |
  'Mailfilled' |
  'Mailoutlined' |
  'Margaritafilled' |
  'Margaritaoutlined' |
  'Menufilled' |
  'Menuoutlined' |
  'Messageaddfilled' |
  'Messageaddoutlined' |
  'Messagecheckmarkfilled' |
  'Messagecheckmarkoutlined' |
  'Messageemptyfilled' |
  'Messageemptyoutlined' |
  'Messageerrorfilled' |
  'Messageerroroutlined' |
  'Messagefilled' |
  'Messagenotificationfilled' |
  'Messagenotificationoutlined' |
  'Messageofffilled' |
  'Messageoffoutlined' |
  'Messageoutlined' |
  'Messagewarningfilled' |
  'Messagewarningoutlined' |
  'Microphonefilled' |
  'Microphoneofffilled' |
  'Microphoneoffoutlined' |
  'Microphoneoutlined' |
  'Minuscirclefilled' |
  'Minuscircleoutlined' |
  'Minusfilled' |
  'Minusoutlined' |
  'Moneyfilled' |
  'Moneyoutlined' |
  'Morecirclefilledhorizontal' |
  'Morecirclefilledvertical' |
  'Morecircleoutlinedhorizontal' |
  'Morecircleoutlinedvertical' |
  'Morefilledhorizontal' |
  'Morefilledvertical' |
  'Moreoutlinedhorizontal' |
  'Moreoutlinedvertical' |
  'Motorcyclehelmetfilled' |
  'Motorcyclehelmetoutlined' |
  'Mylocationfilled' |
  'Mylocationoutlined' |
  'Nubankfilled' |
  'Nubankoutlined' |
  'Openfinancefilled' |
  'Openfinanceoutlined' |
  'Paymentwirelessfilled' |
  'Paymentwirelessoutlined' |
  'Peoplefilled' |
  'Peopleoutlined' |
  'Percentfilled' |
  'Percentoutlined' |
  'Personcirclefilled' |
  'Personcircleoutlined' |
  'Personfilled' |
  'Personoutlined' |
  'Personscanfilled' |
  'Personscanoutlined' |
  'Personsettingsfilled' |
  'Personsettingsoutlined' |
  'Personstarfilled' |
  'Personstaroutlined' |
  'Phonefilled' |
  'Phoneoutlined' |
  'Phonestarfilled' |
  'Phonestaroutlined' |
  'Pinfilled' |
  'Pinofffilled' |
  'Pinoffoutlined' |
  'Pinoutlined' |
  'Pixfilled' |
  'Pixoutlined' |
  'Pizzafilled' |
  'Pizzaoutlined' |
  'Placeholderfilled' |
  'Placeholderoutlined' |
  'Qrcodefilled' |
  'Qrcodeoutlined' |
  'Radiobuttonsfilledselected' |
  'Radiobuttonsfilledunselected' |
  'Radiobuttonsoutlinedselected' |
  'Radiobuttonsoutlinedunselected' |
  'Raycirclefilled' |
  'Raycircleoutlined' |
  'Rayfilled' |
  'Rayofffilled' |
  'Rayoffoutlined' |
  'Rayoutlined' |
  'Receiptfilled' |
  'Receiptoutlined' |
  'Reorderfilledhorizontal' |
  'Reorderfilledvertical' |
  'Reorderoutlinedhorizontal' |
  'Reorderoutlinedvertical' |
  'Resizehandlefilled' |
  'Resizehandleoutlined' |
  'Returnablefilled' |
  'Returnableoutlined' |
  'Savefilled' |
  'Saveoutlined' |
  'Searchfilled' |
  'Searchoutlined' |
  'Sendfilled' |
  'Sendoutlined' |
  'Settingsfilled' |
  'Settingsoutlined' |
  'Sharefilled' |
  'Shareoutlined' |
  'Shieldaddfilled' |
  'Shieldaddoutlined' |
  'Shieldcheckmarkfilled' |
  'Shieldcheckmarkoutlined' |
  'Shieldclockfilled' |
  'Shieldclockoutlined' |
  'Shielddismissfilled' |
  'Shielddismissoutlined' |
  'Shieldfilled' |
  'Shieldhelpfilled' |
  'Shieldhelpoutlined' |
  'Shieldlockfilled' |
  'Shieldlockoutlined' |
  'Shieldoutlined' |
  'Shieldpersonfilled' |
  'Shieldpersonoutlined' |
  'Shieldwarningfilled' |
  'Shieldwarningoutlined' |
  'Shoppingbagfilled' |
  'Shoppingbagoutlined' |
  'Skipback10filled' |
  'Skipback10outlined' |
  'Skipback15filled' |
  'Skipback15outlined' |
  'Skipforward10filled' |
  'Skipforward10outlined' |
  'Skipforward15filled' |
  'Skipforward15outlined' |
  'Snowflakefilled' |
  'Snowflakeoutlined' |
  'Sparklingfilled' |
  'Sparklingoutlined' |
  'Spinnerfilled' |
  'Spinneroutlined' |
  'Sportsoccerfilled' |
  'Sportsocceroutlined' |
  'Starcirclefilled' |
  'Starcircleoutlined' |
  'Starfilled' |
  'Starhalf' |
  'Staroutlined' |
  'Startadafilled' |
  'Startadaoutlined' |
  'Storeeditfilled' |
  'Storeeditoutlined' |
  'Storefilled' |
  'Storelocationfilled' |
  'Storelocationoutlined' |
  'Storeoutlined' |
  'Storesettingsfilled' |
  'Storesettingsoutlined' |
  'Storestarfilled' |
  'Storestaroutlined' |
  'Tacofilled' |
  'Tacooutlined' |
  'Tadafilled' |
  'Tadaoutlined' |
  'Teafilled' |
  'Teaoutlined' |
  'Thermometerhighfilled' |
  'Thermometerhighoutlined' |
  'Thermometerlowfilled' |
  'Thermometerlowoutlined' |
  'Thermometermediumfilled' |
  'Thermometermediumoutlined' |
  'Thumbdownfilled' |
  'Thumbdownoutlined' |
  'Thumbupfilled' |
  'Thumbupoutlined' |
  'Ticketfilled' |
  'Ticketoutlined' |
  'Tiktokfilled' |
  'Tiktokoutlined' |
  'Trashfilled' |
  'Trashoutlined' |
  'Trophyfilled' |
  'Trophyoutlined' |
  'Umbrellafilled' |
  'Umbrellaoutlined' |
  'Vehiclemotorcyclefilled' |
  'Vehiclemotorcycleoutlined' |
  'VehicletruckCheckmarkfilled' |
  'VehicletruckCheckmarkoutlined' |
  'VehicletruckClockfilled' |
  'VehicletruckClockoutlined' |
  'VehicletruckErrorfilled' |
  'VehicletruckErroroutlined' |
  'VehicletruckFastfilled' |
  'VehicletruckFastoutlined' |
  'VehicletruckRayfilled' |
  'VehicletruckRayoutlined' |
  'VehicletruckWarningfilled' |
  'VehicletruckWarningoutlined' |
  'Vehicletruckfilled' |
  'Vehicletruckoutlined' |
  'Walletfilled' |
  'Walletofffilled' |
  'Walletoffoutlined' |
  'Walletoutlined' |
  'Walletreceivefilled' |
  'Walletreceiveoutlined' |
  'Walletsendfilled' |
  'Walletsendoutlined' |
  'Walletstarfilled' |
  'Walletstaroutlined' |
  'Warningcirclefilled' |
  'Warningcircleoutlined' |
  'Warningtrianglefilled' |
  'Warningtriangleoutlined' |
  'Whatsappfilled' |
  'Whatsappoutlined' |
  'WiFifilled' |
  'WiFiofffilled' |
  'WiFioffoutlined' |
  'WiFioutlined' |
  'Winefilled' |
  'Wineoutlined' |
  'Wineryfilled' |
  'Wineryoutlined' |
  'Xfilled' |
  'Xoutlined' |
  'Zoominfilled' |
  'Zoominoutlined' |
  'Zoomoutfilled' |
  'Zoomoutoutlined' |
  'Zéfilled' |
  'Zéoutlined' |
  'Zépontosfilled' |
  'Zépontosoutlined'

/**
 * Common Icon Props
 */
export interface IconProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  color?: string
  width?: string | number
  height?: string | number
  className?: string
}
